---
title: "Kanäle und Medien des digitalen Marketings"
author: "Thomas Schmid, Damian Krebs"
date: "12 6 2020"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include=FALSE}
library(dplyr)
library(tidyverse)
library(magrittr)
library(knitr)
library(dplyr)
```


```{r echo=FALSE, include = FALSE}
library(tidyverse)

dat <- read.csv2('D:\\Desktop\\BIT\\Bachelor\\06_Auswertung\\Angepasste Tabelle.csv')
q1_Suchmaschine <-  subset(dat, select=c("Nummer", "X01_1", "X01_2", "X01_3", "X01_4", "X01_5", "X01_6", "X01b"))
q1_Suchmaschine <-  q1_Suchmaschine %>% rename(google = X01_1, bing = X01_2, yahoo = X01_3, search.ch = X01_4 , escosia.org = X01_5, Andere =X01_6, TextAndere = X01b)

levels = c("nie", "selten", "monatlich","wöchentlich","nahezu täglich")
q1_SuchmaschineAngepasst <- q1_Suchmaschine %>% subset(select =c(Nummer, google, bing, yahoo, search.ch, escosia.org, Andere)) %>% 
  mutate(
  google = case_when(
    google == 1 ~ levels[1], 
    google == 2 ~ levels[2], 
    google == 3 ~ levels[3],
    google == 4 ~ levels[4],
    google == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels),
  bing = case_when(
    bing == 1 ~ levels[1], 
    bing == 2 ~ levels[2], 
    bing == 3 ~ levels[3],
    bing == 4 ~ levels[4],
    bing == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels),
  yahoo = case_when(
    yahoo == 1 ~ levels[1], 
    yahoo == 2 ~ levels[2], 
    yahoo == 3 ~ levels[3],
    yahoo == 4 ~ levels[4],
    yahoo == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels),
  search.ch = case_when(
    search.ch == 1 ~ levels[1], 
    search.ch == 2 ~ levels[2], 
    search.ch == 3 ~ levels[3],
    search.ch == 4 ~ levels[4],
    search.ch == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels),
  escosia.org = case_when(
    escosia.org == 1 ~ levels[1], 
    escosia.org == 2 ~ levels[2], 
    escosia.org == 3 ~ levels[3],
    escosia.org == 4 ~ levels[4],
    escosia.org == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels),
  Andere = case_when(
    Andere == 1 ~ levels[1], 
    Andere == 2 ~ levels[2], 
    Andere == 3 ~ levels[3],
    Andere == 4 ~ levels[4],
    Andere == 5 ~ levels[5],
    TRUE ~  levels[1]) %>% factor(levels))

q1_SuchmaschineAngepasst <- q1_SuchmaschineAngepasst %>% gather(google, bing, yahoo, search.ch, escosia.org, Andere, key = Suchmaschine, value = Frequenz)

q1_SuchmaschineAngepasst$Suchmaschine <- as.factor(q1_SuchmaschineAngepasst$Suchmaschine)
q1_SuchmaschineAngepasst$Frequenz <- as.factor(q1_SuchmaschineAngepasst$Frequenz)
q1_SuchmaschineAngepasst$Suchmaschine <- factor(q1_SuchmaschineAngepasst$Suchmaschine, levels = c("google", "bing", "yahoo","search.ch","escosia.org", "Andere"))
q1_SuchmaschineAngepasst$Frequenz <- factor(q1_SuchmaschineAngepasst$Frequenz, levels = c("nie", "selten", "monatlich","wöchentlich","nahezu täglich"))

q2_3_4_5_bezahlteLinks <- subset(dat, select=c("Nummer", "X2","X3","X4","X5"))
q2_3_4_5_bezahlteLinks <- q2_3_4_5_bezahlteLinks %>% rename(ZweiteSeite = X2, ProzentBezahlteLinks = X3, ProzentKaufBezahlteLinks = X4, ZweckKauf = X5)

q6_VewendungSozialMedia <- subset(dat, select=c("Nummer", "X06_1", "X06_2", "X06_3", "X06_4", "X06_5", "X06_6", "X06_7", "X06_8", "X06b"))
q6_VewendungSozialMedia <-  q6_VewendungSozialMedia %>% rename(Facebook = X06_1, Instagram = X06_2, YouTube = X06_3, Twitter = X06_4 , LinkedIn = X06_5, Spnapchat =X06_6, TikTok =X06_7, Andere =X06_8, AndereText = X06b)

q7_SucheProduktSozialMedia <- subset(dat, select=c("Nummer", "X07_1", "X07_2"))
q7_SucheProduktSozialMedia <- q7_SucheProduktSozialMedia %>% rename(privat = X07_1, geschäftlich = X07_2)

q8_KommunikationUnternehmen <- subset(dat, select=c("Nummer", "X08_1", "X08_2"))
q8_KommunikationUnternehmen <- q8_KommunikationUnternehmen %>% rename(privat = X08_1, geschäftlich = X08_2)

q9_KommunikationUnternehmenhaufig <- subset(dat, select=c("Nummer", "X09_1", "X09_2"))
q9_KommunikationUnternehmenhaufig <- q9_KommunikationUnternehmenhaufig %>% rename(privat = X09_1, geschäftlich = X09_2)

q10_Unternehmeneinkauf <- subset(dat, select=c("Nummer", "X10_1", "X10_2"))
q10_Unternehmeneinkauf <- q10_Unternehmeneinkauf %>% rename(privat = X10_1, geschäftlich = X10_2)

q11_UnternehmeneinkaufKonkurrenz <- subset(dat, select=c("Nummer", "X11_1", "X11_2"))
q11_UnternehmeneinkaufKonkurrenz <- q11_UnternehmeneinkaufKonkurrenz %>% rename(privat = X11_1, geschäftlich = X11_2)

q12_likseinkauf <- subset(dat, select=c("Nummer", "X12_1", "X12_2"))
q12_likseinkauf <- q12_likseinkauf %>% rename(privat = X12_1, geschäftlich = X12_2)

q13_SucheProduktprivate <- subset(dat, select=c("Nummer", "X13.1_1", "X13.1_2", "X13.1_3", "X13.1_4", "X13.1_5", "X13.1_6"))
q13_SucheProduktprivate <- q13_SucheProduktprivate %>% rename(Vergleichsdienste = X13.1_1, Blogs = X13.1_2, Influencer = X13.1_3, Freunde = X13.1_4, Mitarbeiter = X13.1_5, SocialMedia = X13.1_6 )

q13_SucheProduktfirm <- subset(dat, select=c("Nummer", "X13.2_1", "X13.2_2", "X13.2_3", "X13.2_4", "X13.2_5", "X13.2_6"))
q13_SucheProduktfirm <- q13_SucheProduktfirm %>% rename(Vergleichsdienste = X13.2_1, Blogs = X13.2_2, Influencer = X13.2_3, Freunde = X13.2_4, Mitarbeiter = X13.2_5, SocialMedia = X13.2_6 )

q14_Vertrauen <- subset(dat, select=c("Nummer", "X14_1", "X14_2", "X14_3", "X14_4", "X14_5", "X14_6", "X14_7", "X14_8"))
q14_Vertrauen <-  q14_Vertrauen %>% rename(Vergleichsdienste = X14_1, Blogs = X14_2, Influencer = X14_3, Freunde = X14_4, Mitarbeiter = X14_5, Webseite = X14_6, SocialMedia = X14_7, Email = X14_8)

q15_EmailNewsletter <- subset(dat, select=c("Nummer", "X15_1_1", "X15_1_2", "X15_2_1", "X15_2_2","X15_3_1", "X15_3_2","X15_4_1", "X15_4_2","X15_5_1", "X15_5_2","X15_6_1", "X15_6_2"))
q15_EmailNewsletter <- q15_EmailNewsletter  %>% rename(IntressePrivat = X15_1_1, IntesseFirma = X15_1_2,
                                                       AktionenPrivat = X15_2_1, AktionenFirma = X15_2_2,
                                                       AngebotPrivat = X15_3_1, AngebotFirma = X15_3_2,
                                                       InhaltPrivat = X15_4_1, InhaltFirma = X15_4_2,
                                                       TrendsPrivat = X15_5_1, TrendsFirma = X15_5_2,
                                                       UnternehmenPrivat = X15_6_1, UnternehmenFirma = X15_6_2)

q16_NichtAbonniert <- subset(dat, select=c("Nummer", "X16_1", "X16_2"))
q16_NichtAbonniert <- q16_NichtAbonniert %>% rename(privat = X16_1, geschäftlich = X16_2)

q17_BevorzugteKommunikation <- subset(dat, select=c("Nummer", "X17_1", "X17_2", "X17_3", "X17_4","X17_5", "X17_6","X17_7", "X17_8","X17_9", "X17_10","X17_10_TEXT"))
q17_BevorzugteKommunikation <- q17_BevorzugteKommunikation  %>% rename(Email = X17_1, Brief = X17_2,
                                                       MobileApp = X17_3, SocialMedia = X17_4,
                                                       Messanger = X17_5, SMS = X17_6,
                                                       Telefon = X17_7, Chatbots = X17_8,
                                                       ServiceProtale = X17_9, Andere = X17_10,
                                                       AndereText = X17_10_TEXT)

q18_QuellenSuche <- subset(dat, select=c("Nummer", "X18_1", "X18_2", "X18_3", "X18_4","X18_5", "X18_6","X18_7", "X18_8","X18_9", "X18_10", "X18_11","X18b"))
q18_QuellenSuche <- q18_QuellenSuche  %>% rename(Suchmaschine = X18_1, Vergleichsdienst = X18_2,
                                                 Blogs = X18_3, Influencer = X18_4,
                                                 Facebook = X18_5, Instagram = X18_6,
                                                 YouTube = X18_7, Twitter = X18_8,
                                                 Linkedin = X18_9, TikTok = X18_10,
                                                 Andere = X18_11, AndereText = X18b )

q19_QuellenKauf <- subset(dat, select=c("Nummer", "X19_1", "X19_2", "X19_3", "X19_4","X19_5", "X19_6","X19_7", "X19_8","X19_9", "X19_10"))
q19_QuellenKauf <- q19_QuellenKauf  %>% rename(Suchmaschine = X19_1, Vergleichsdienst = X19_2,
                                                 Blogs = X19_3, Influencer = X19_4,
                                                 Facebook = X19_5, Instagram = X19_6,
                                                 YouTube = X19_7, Twitter = X19_8,
                                                 Linkedin = X19_9, TikTok = X19_10)

q20_MediumAktuell <- subset(dat, select=c("Nummer", "X20", "X20_5_TEXT"))
q20_MediumAktuell <- q20_MediumAktuell %>% rename(Medium = X20, Andere = X20_5_TEXT)

q21_MediumZukunft <- subset(dat, select=c("Nummer", "X21", "X21_5_TEXT"))
q21_MediumZukunft <- q21_MediumZukunft %>% rename(Medium = X21, Andere = X21_5_TEXT)

q22_MediumVorteil <- subset(dat, select=c("Nummer", "X22_1", "X22_2", "X22_3", "X22_4", "X22_5", "X22_5_TEXT"))
q22_MediumVorteil <- q22_MediumVorteil %>% rename(Text = X22_1, Bilder = X22_2,
                                                  Audio = X22_3, Video =X22_4,
                                                 Andere = X22_5, AndereText = X22_5_TEXT)

q23_Geschlecht <- subset(dat, select=c("Nummer", "X23"))
q23_Geschlecht <- q23_Geschlecht %>% rename(Geschlecht = X23)
levels = c("männlich", "weiblich", "Keine Auswahl")
q23_Geschlecht <- q23_Geschlecht %>% mutate(GeschlechtText = case_when(Geschlecht == 1 ~ levels[1], Geschlecht == 2 ~ levels[2], TRUE ~  levels[3]) %>% factor(levels))


q24_Alter <- subset(dat, select=c("Nummer", "X24"))
q24_Alter <- q24_Alter %>% rename(Alter = X24)

levels = c("unter 18 Jahre", "18-25", "26-32","33-40","41-55","56-65","über 65 Jahre", "Leer")
q24_Alter <- q24_Alter %>% mutate(AlterText = case_when(
  Alter == 1 ~ levels[1], 
  Alter == 2 ~ levels[2], 
  Alter == 3 ~ levels[3],
  Alter == 4 ~ levels[4],
  Alter == 5 ~ levels[5],
  Alter == 6 ~ levels[6],
  Alter == 7 ~ levels[7],
  TRUE ~  levels[8]) %>% factor(levels))

q1_SuchmaschineJoined <- left_join(q1_SuchmaschineAngepasst,q23_Geschlecht, by = "Nummer")
q1_SuchmaschineJoined <- left_join(q1_SuchmaschineJoined, q24_Alter, by = "Nummer")

q24_AlterJoined <- left_join(q24_Alter,q23_Geschlecht, by = "Nummer")

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

getfrequenz <- function(x, NumberOfItems, RowNamesLevels, ColumnNames){
  numberofColumns <- ncol(x)
  numberofRows <-  nrow(x)
  items <- c(1:NumberOfItems)
  itemscolums <- c(1: numberofColumns)
  
  
  resultDataframe <- data.frame(Feld = RowNamesLevels)
  
  for(itemNumber in items){
    columnname = ColumnNames[itemNumber]
    resultDataframe <- resultDataframe %>% mutate(UQ(rlang::sym(columnname)) := "0.00% 0")
  }
  
  for(numberofCurrentColumn in itemscolums){
    
    numbers <- transform(as.data.frame(table(x[numberofCurrentColumn])), percentage = round(Freq/nrow(x)*100, digits = 2))
    numbers$Var1 <- as.numeric(as.character(numbers$Var1))
    
    for(val in items)
    {
      if(!is.na(numbers[val,1]))
      {
        columnnumber <- as.numeric(numbers[val,1]) +1
        rownumber <- numberofCurrentColumn
        
        resultDataframe[rownumber,columnnumber] <- paste(as.character(numbers[val,3]), "%\t",as.character(numbers[val,2]), sep ="")
        
      }
    }
  }
  
  return(resultDataframe)
}
  


```

## Geschlecht Teilnehmende

```{r geschlecht, echo=FALSE}
q23_Geschlecht %>% ggplot(aes(x= GeschlechtText, fill = GeschlechtText)) + labs(x = "Geschlecht", fill = "Geschlecht", y="Anzahl")  + geom_bar() + geom_text(aes(label =stat(count)), stat= 'count', position = position_stack(vjust = .5),color="white") + scale_fill_manual(values=c("#0703f0", "#c74dc2", "#85796f"))

q23 <- data.frame(Bezeichnung =c(
                                  "Männlich",
                                  "Weiblich",
                                  "Standardabweichung", 
                                  "Mittelwert",
                                  "Median",
                                  "Modus"),
                  Wert = c(
                    "1",
                    "2",
                    round(sd(q23_Geschlecht$Geschlecht, na.rm = TRUE),digits=6), 
                    round(mean(q23_Geschlecht$Geschlecht, na.rm = TRUE),digits=6),
                    round(median(q24_Alter$Alter, na.rm = TRUE),digits=6),
                    getmode(q24_Alter$Alter)))

knitr::kable(
  q23, longtable = TRUE, booktabs = TRUE,
  caption = "Werte Geschlecht"
)

```


## Alter Teilnehmende

```{r alter, echo=FALSE}
q24_Alter %>% ggplot(aes(x= AlterText, fill = AlterText)) + labs(x = "Alter", fill = "Alter", y="Anzahl")  + geom_bar() + geom_text(aes(label =stat(count)), stat= 'count', position = position_stack(vjust = .5))

q24_AlterJoined %>% ggplot(aes(x=AlterText, fill =GeschlechtText))+ labs(x = "Alter", y="Anzahl")  + geom_bar() + geom_text(aes(label =stat(count)), stat= 'count', position = position_stack(vjust = .5), color ="white")+ scale_fill_manual(values=c("#0703f0", "#c74dc2", "#85796f"))

q24 <- data.frame(Bezeichnung =c(
                                  "unter 18 Jahre",
                                  "18-25",
                                  "26-32", 
                                  "33-40",
                                  "41-55",
                                  "56-65",
                                  "über 65 Jahre",
                                  "Standardabweichung", 
                                  "Mittelwert",
                                  "Median",
                                  "Modus"),
                  Wert = c(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    round(sd(q24_Alter$Alter, na.rm = TRUE),digits=6), 
                    round(mean(q24_Alter$Alter, na.rm = TRUE),digits=6),
                    round(median(q24_Alter$Alter, na.rm = TRUE),digits=6),
                    getmode(q24_Alter$Alter)))

knitr::kable(
  q24, longtable = TRUE, booktabs = TRUE,
  caption = "Werte Alter"
)

```


## Suchmaschienenpreferenzen

```{r Suchmaschine, echo=FALSE}

q1_SuchmaschineAngepasst %>% ggplot(aes(x=Frequenz, fill= Suchmaschine)) + geom_bar(position = "dodge2") + xlab("Frequenz") + ylab("Anzahl") + coord_flip()

q1_SuchmaschineJoined %>% ggplot(aes(x=Frequenz, fill= Suchmaschine)) + geom_bar(position = "dodge2") + xlab("Frequenz") + ylab("Anzahl") + facet_wrap(.~AlterText)  + coord_flip()

q1_SuchmaschineJoined %>% ggplot(aes(x=Frequenz, fill= Suchmaschine)) + geom_bar(position = "dodge2") + xlab("Frequenz") + ylab("Anzahl") + facet_wrap(.~GeschlechtText)  + coord_flip()


q1 <- data.frame(Bezeichnung =c(
                                  "nie",
                                  "selten",
                                  "monatlich", 
                                  "wöchentlich",
                                  "nahezu täglich"),
                  Wert = c(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"))

knitr::kable(
  q1, longtable = TRUE, booktabs = TRUE,
  caption = "Werte Freqeunz"
)

q1_1 <- getfrequenz(subset(q1_Suchmaschine, select = c(google, bing, yahoo, search.ch, escosia.org, Andere)),5,levels(q1_SuchmaschineJoined$Suchmaschine), c(
  "nie",
  "selten",
  "monatlich", 
  "wöchentlich",
  "nahezu täglich"))

knitr::kable(
  q1_1, longtable = TRUE, booktabs = TRUE,
  caption = "Werte Freqeunz"
)




```

